# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145Ze5soyGhnO_lOGlUdMGYT0W38z-tMk
"""

import pickle
import requests
import io
import streamlit as st

# URL of the raw model file on GitHub
model_url = 'https://raw.githubusercontent.com/ayeshayousaf24/streamlit_svm_app/main/svm_model.pkl'

# Download the model file
response = requests.get(model_url)

# Check if the response is successful
if response.status_code == 200:
    try:
        # Use io.BytesIO to read the byte stream
        model = pickle.load(io.BytesIO(response.content))
        st.success("Model loaded successfully!")
    except Exception as e:
        st.error(f"Error loading model: {e}")
else:
    st.error(f"Failed to download the model. Status code: {response.status_code}")

def main():
  st.title('Product Buying Prediction App')

  #input Variables
  Gender = st.text_input('Gender')
  Age = st.text_input('Age')
  Estimated_salary = st.text_input('EstimatedSalary')

  #Predicted Code
  if st.button('Predict'):
    makeprediction = model.predict([[Gender, Age, Estimated_salary]])
    output = round(makeprediction[0], 2)
    if st.success(makeprediction):  # Replace 'condition' with your actual condition
        print('This user can buy the product', format(output))
    else:
        print('This user cannot buy the product', format(output))

if __name__ == '__main__':
    main()
