# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145Ze5soyGhnO_lOGlUdMGYT0W38z-tMk
"""

import pickle
import streamlit as st

model = pickle.load(open('/content/svm_model.pkl', 'rb'))

def main():
  st.title('Product Buying Prediction App')

  #input Variables
  Gender = st.text_input('Gender')
  Age = st.text_input('Age', min_value=0, max_value=120, step=1)
  Estimated_salary = st.text_input('EstimatedSalary', min_value=0, step=1000000)

  #Predicted Code
  if st.button('Predict'):
    makeprediction = model.predict([[Gender, Age, Estimated_salary]])
    output = round(makeprediction[0], 2)
    if st.success(makeprediction):  # Replace 'condition' with your actual condition
        print('This user can buy the product', format(output))
    else:
        print('This user cannot buy the product', format(output))

if __name__ == '__main__':
    main()